# Generated by Django 3.2.8 on 2021-11-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0003_acad_level_employee_gender_level_race_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='table1',
        ),
        migrations.AlterField(
            model_name='acad_level',
            name='acad_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='icon_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gender',
            name='gender',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='race',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
