# Generated by Django 3.2.8 on 2021-11-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0008_alter_location_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='company',
            field=models.ManyToManyField(to='TestApp.Company'),
        ),
    ]
